"""Build local video posters and intrinsic dimensions. Originals are never changed.

Requires Pillow and imageio-ffmpeg (or ffmpeg on PATH).
Run from any directory: python scripts/build-media.py
"""

import hashlib
import io
import json
from pathlib import Path
import re
import shutil
import subprocess
from urllib.parse import unquote

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
POSTERS = ROOT / "_posters"


def read_data(html, name):
    offset = html.index("const " + name + "=") + len("const " + name + "=")
    return json.JSONDecoder().raw_decode(html[offset:])[0]


def main():
    html = (ROOT / "index.html").read_text(encoding="utf-8")
    works = read_data(html, "works")
    poster_times = {unquote(work["cover"]):work.get("posterTime", 2) for work in works}
    target = ROOT / "assets" / "media-info.js"
    previous = {}
    if target.exists():
        previous = json.loads(target.read_text(encoding="utf-8").split("window.PORTFOLIO_MEDIA=", 1)[1].strip().removesuffix(";"))
    sources = set()
    for work in works:
        sources.update(filter(None, [work.get("cover"), work.get("detailCover")]))
        sources.update(work.get("images", []))
    sources.update(re.findall(r"(?:sectionHeroCover|wechatQR)[:=]'([^']+)'", html))
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        from imageio_ffmpeg import get_ffmpeg_exe
        ffmpeg = get_ffmpeg_exe()
    POSTERS.mkdir(exist_ok=True)
    metadata = {}
    for src in sorted({unquote(src).replace("\\", "/").removeprefix("./") for src in sources}):
        path = (ROOT / src).resolve()
        if not path.is_relative_to(ROOT):
            raise ValueError("Media path is outside the project: " + src)
        if path.suffix.lower() in {".mp4", ".webm", ".mov"}:
            poster = POSTERS / (hashlib.sha256(src.encode()).hexdigest()[:16] + ".webp")
            poster_time = poster_times.get(src, 2)
            if (not poster.exists() or poster.stat().st_mtime < path.stat().st_mtime or
                    previous.get(src, {}).get("posterTime") != poster_time):
                for timestamp in (poster_time, 0):
                    result = subprocess.run([
                        ffmpeg, "-hide_banner", "-loglevel", "error", "-ss", str(timestamp),
                        "-i", str(path), "-frames:v", "1", "-vf", "scale='min(1280,iw)':-2",
                        "-f", "image2pipe", "-vcodec", "png", "-threads", "1", "-"
                    ], capture_output=True, check=True)
                    if result.stdout:
                        break
                with Image.open(io.BytesIO(result.stdout)) as frame:
                    frame.convert("RGB").save(poster, "WEBP", quality=78, method=6)
            with Image.open(poster) as image:
                metadata[src] = {"width":image.width, "height":image.height,
                                 "poster":poster.relative_to(ROOT).as_posix(), "posterTime":poster_time}
        else:
            with Image.open(path) as image:
                metadata[src] = {"width":image.width, "height":image.height}
    target.parent.mkdir(exist_ok=True)
    target.write_text("// Generated by scripts/build-media.py; do not edit.\nwindow.PORTFOLIO_MEDIA=" +
                      json.dumps(metadata, ensure_ascii=False, separators=(",", ":"), sort_keys=True) +
                      ";\n", encoding="utf-8")
    videos = [entry for entry in metadata.values() if "poster" in entry]
    print(json.dumps({"assets":len(metadata), "posters":len(videos),
                      "posterBytes":sum((ROOT / entry["poster"]).stat().st_size for entry in videos)}))


if __name__ == "__main__":
    main()
